FROM node:12.2.0-alpine as build

LABEL maintainer="Dmitry Kisler" \
      email=admin@dkisler.com \
      web=www.dkisler.com

WORKDIR /app-base

COPY ./app-base/package.json .
RUN yarn

COPY ./app-base .
RUN yarn build

FROM fnichol/uhttpd

WORKDIR /www

COPY --from=build /app-base/build .
