FROM node:12.2.0-alpine

LABEL maintainer="Dmitry Kisler" \
      email=admin@dkisler.com \
      web=www.dkisler.com

RUN mkdir -p /app-base/src /app-base/public

WORKDIR /app-base

COPY ./app-base/package.json ./
COPY ./app-base/.env ./
COPY ./app-base/src ./src
COPY ./app-base/public ./public

RUN yarn install
RUN yarn build
RUN yarn global add serve

ENV PORT 80

CMD serve -s build -p ${PORT}
