version:          '3.7'

services:

  backend_base:
    build:
      context:    './backend'
      dockerfile: 'service_base/Dockerfile'
    ports:
      - "10002:4500"

  backend_ml:
    build:
      context:    './backend'
      dockerfile: 'service_ml/Dockerfile'
    ports:
      - "10003:4500"

  frontend_base:
    build:
      context:    './frontend'
      dockerfile: 'Dockerfile-base'
    ports:
      - "10000:80"

  frontend:
    build:
      context:    './frontend'
      dockerfile: 'Dockerfile'
    ports:
      - "10001:80"
