version: '3.7'

services:

  backend_base:
    build:
      context: './backend'
      dockerfile: 'service_base/Dockerfile'
    ports:
      - "${PORT_BE_BASE}:4499"

  backend_ml:
    build:
      context: './backend'
      dockerfile: 'service_ml/Dockerfile'
    ports:
      - "${PORT_BE_ML}:4500"

  frontend:
    build:
      context: './frontend'
      args:
        APIURL_BASE: ${BACKEND_API_BASE}
        APIURL_ML: ${BACKEND_API_ML}
    ports:
      - "${PORT_FE}:80"
