version:          '3.7'

services:

  server-color_name:
    build:
      context:    './server'
      dockerfile: 'color_name/Dockerfile'
    ports:
      - "${PORT_BE_NAME}:4500"

  server-color_type:
    build:
      context:    './server'
      dockerfile: 'color_type/api/Dockerfile'
    ports:
      - "${PORT_BE_TYPE}:4500"

  client:
    build:
      context:    './client'
      dockerfile: 'Dockerfile'
      args: 
        URL_BACKEND_NAME: ${BACKEND_API_NAME}
        URL_BACKEND_TYPE: ${BACKEND_API_TYPE}
    ports:
      - "${PORT_FE}:80"