version: '3.7'

services:
  backend_base:
    build: './backend/service_base'
    ports:
      - "${PORT_BE_BASE}:4499"
  backend_ml:
    build: './backend/service_ml'
    ports:
      - "${PORT_BE_ML}:4500"
  frontend:
    build:
      context: './frontend'
      args:
        APIURL_BASE: ${BACKEND_API_BASE}
        APIURL_ML: ${BACKEND_API_ML}
    ports:
      - "${PORT_FE}:80"
