version:             '3.7'

services:

  backend_base:
    build:
      context:       './backend'
      dockerfile:    'service_base/Dockerfile'
    ports:
      - "${PORT_BE_BASE}:4500"

  backend_ml:
    build:
      context:       './backend'
      dockerfile:    'service_ml/Dockerfile'
    ports:
      - "${PORT_BE_ML}:4500"

  frontend_base:
    build:
      context:       './frontend'
      dockerfile:    'Dockerfile-base'
      args:
        APIURL_BASE: ${BACKEND_API_BASE}
    ports:
      - "10000:80"

  frontend:
    build:
      context:       './frontend'
      dockerfile:    'Dockerfile'
      args:
        APIURL_BASE: ${BACKEND_API_BASE}
        APIURL_ML:   ${BACKEND_API_ML}
    ports:
      - "10001:80"
